export const SET__SINGLE__PRODUCT = "SET__SINGLE__PRODUCT";
export const REMOVE__SINGLE__PRODUCT = "REMOVE__SINGLE__PRODUCT";
export const ADD__PRODUCT__TO__CART = "ADD__PRODUCT__TO__CART";
export const DELETE__PRODUCT__IN__CART = "DELETE__PRODUCT__IN__CART";
export const CLEAR__PRODUCT__CART = "CLEAR__PRODUCT__CART";
export const CHANGE__PRODUCT__CART = "CHANGE__PRODUCT__CART";
